### ISSUE TITLE
Ошибка в Lesson 6

### ISSUE THREAD

**Issue by Fayst2D** [satma0745/ASP-Courses#1]
В методе DeleteMeetup компилятор выдаёт ошибку в строчке с присвоением Id
![image](https://user-images.githubusercontent.com/35884825/163675927-0a35acff-cc8f-464d-822b-d53d51ea1aea.png)
Из-за того что айди в модели митапа nullable
![image](https://user-images.githubusercontent.com/35884825/163675986-5b455b5b-24b7-4577-8df7-9f22f80727ff.png)

**Comment by satma0745** [comment]
Can, You, please, share Your's `Meetup` model definition?

**Comment by satma0745** [comment]
Благодарю за заведённый Issue. Проблема в том, что модель `Meetup` объявлена некорректно - необходимо заменить `public Guid? Id { get; set; }` на `public Guid Id { get; set; }`. В ближайшее время обновлю урок, чтобы отразить это изменение.
