### ISSUE TITLE
Возможно опечатка

### ISSUE THREAD

**Issue by Fayst2D** [satma0745/ASP-Courses#2]
В Lesson 9 в пункте [Установка и настройка СУБД](https://github.com/satma0745/ASP-Courses/blob/main/Lesson%2009/Readme.md#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D1%83%D0%B1%D0%B4) утилита называется `pgsql`
![image](https://user-images.githubusercontent.com/35884825/163724980-adbfffae-240e-4d8b-9c38-edc4eea67569.png)
но как я понял на самом деле она называется `psql`
![image](https://user-images.githubusercontent.com/35884825/163725020-ce814e63-6114-4b94-90d3-2f19e2ab192b.png)

**Comment by satma0745** [comment]
Да, 100% очепятка. Утилита называется `psql`
