### ISSUE TITLE
Не работает консольная команда

### ISSUE THREAD

**Issue by Fayst2D** [satma0745/ASP-Courses#3]
В Lesson 9 в пункте [Установка библиотек и инструментов](https://github.com/satma0745/ASP-Courses/blob/main/Lesson%2009/Readme.md#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA-%D0%B8-%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2) неправильно написана консольная команда 
```
dotnet tool install dotnet-ef
```

В документации она записана так
```
dotnet tool install --global dotnet-ef
```

**Comment by satma0745** [comment]
Всё тут правильно. Необходимо установить локально, а не глобально.
То, что она в таком виде сразу не заработала – тоже намерено. Тебе нужно будет разобраться с тем, как устанавливать пакеты локально.

**Comment by Fayst2D** [comment]
Ясно, спасибо
