### ISSUE TITLE
небольшая опечятка

### ISSUE THREAD

**Issue by Fayst2D** [satma0745/ASP-Courses#4]
[тут](https://github.com/satma0745/ASP-Courses/blob/main/Lesson%2010/Readme.md#%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8-%D0%BF%D0%BE%D0%BB%D0%B5%D0%B9-%D0%B8-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86-%D0%B2-postgresql) в самом низу
![image](https://user-images.githubusercontent.com/35884825/164512256-4c6f00c7-8891-403d-82c7-6000474011d7.png)
как я понял здесь должно быть `snake_case`

P.S. Нормально ли я issues оформляю ?

**Comment by satma0745** [comment]
Да, спасибо большое за то, что этим занимаешься
