### ISSUE TITLE
После добавления AutoMapper не хэшируется пароль

### ISSUE THREAD

**Issue by nik0laevvlad** [satma0745/ASP-Courses#6]
В 14 уроке после добавления AutoMapper если зарегистрировать нового пользователя и открыть таблицу пользователей, в базе сохранится сам пароль, а не его хэш

**Comment by satma0745** [comment]
Так ведь используется `BCrypt` для хеширования: https://github.com/satma0745/ASP-Courses/blob/788724dff6dd5abda831a775211e1c3ca5125df4/Lesson%2014/src/User/Controller.cs#L66

**Comment by satma0745** [comment]
А, в самом Readme урока не указано:
![image](https://user-images.githubusercontent.com/54468544/165029624-124b405a-76ba-4925-afba-be6452bbab4c.png)
